apiVersion: v1
kind: PersistentVolume

metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres

spec:
  storageClassName: manual
  capacity:
    storage: 10Gi

  accessModes:
    - ReadWriteMany

  hostPath:
    path: "/var/lib/postgres"

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pv-claim
  labels:
    app: postgres

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: postgres

  replicas: 1

  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.2-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mole_dev
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mole-secret
                  key: postgres_user
            - name: PASTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mole-secret
                  key: postgres_password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "500m"
              memory: 1Gi
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: v1
kind: Service

metadata:
  name: postgres

  labels:
    app: postgres

spec:
  ports:
    - port: 5432

  selector:
    app: postgres
