apiVersion: apps/v1

kind: Deployment
metadata:
  name: moles
  namespace: default
  labels:
    app: moles

spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: moles
  replicas: 1

  template:
    metadata:
      labels:
        app: moles

    spec:
      containers:
        - name: moles
          image: davidcroda/wack-a-mole:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: 256Mi
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: PORT
              value: "4000"
            - name: PHX_HOST
              value: "moles.daveroda.com"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: mole-secret
                  key: secret_key_base
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mole-secret
                  key: database_url

---
apiVersion: v1

kind: Service
metadata:
  name: moles
  labels:
    app: moles
spec:
  ports:
    - name: http
      targetPort: 4000
      port: 4000

  selector:
    app: moles
